### ISSUE TITLE
upgrade rust-toolchain.toml to reference nightly-07-08

### ISSUE THREAD

**Issue by mutantbob** [Rahix/avr-hal-template#10]
There is a bug in LLVM regarding MOVW being translated into a pair of 8-bit register moves which could malfunction if the register pairs overlapped.  This was discovered while troubleshooting the ST7789 crate ( https://github.com/almindor/st7789/issues/19 ) and was reported to the rust toolchain as https://github.com/rust-lang/rust/issues/98167 .  The fix appears to be part of `nightly-07-08`, and also sorted out some strange behavior in `ufmt` . 

I recommend that you give nightly-07-08 a try, and if you do not find any showstoppers then make it the default `channel` in `rust-toolchain.toml` .

**Comment by Rahix** [comment]
Already resolved now with 6494918848761c5727dc8ce312e713043162da15.
