### ISSUE TITLE
Error: Malformed URL ''; class=Net (12)

### ISSUE THREAD

**Issue by jmmaa** [Rahix/avr-hal-template#16]
Hi! I'm getting this error when I execute this `cargo-generate` command from the readme
```
D:\github>cargo generate --git https://github.com/Rahix/avr-hal-template.git
Error: Please check if the Git user / repository exists.

Caused by:
    malformed URL ''; class=Net (12)
```

Here is my `cargo-generate` version
```
D:\github>cargo generate -V
cargo generate-generate 0.17.4
```

**Comment by Rahix** [comment]
Hi, sorry, I don't think I can help you here.  Maybe you can ask the cargo-generate people whether they have an idea what's going on?
