### ISSUE TITLE
Running in mac M1 yields error

### ISSUE THREAD

**Issue by dominikwilkowski** [Rahix/avr-hal-template#19]
Error:

```
error: the 'cargo' binary, normally provided by the 'cargo' component, is not applicable to the 'nightly-2022-07-10-aarch64-apple-darwin' toolchain
```

OS & Distribution `macOS 13.4.1 arm64`
cargo version `cargo 1.70.0 (ec8a8a0ca 2023-04-25)`
rustc version `rustc 1.70.0 (90c541806 2023-05-31)`

No changes to the template at all

**Comment by Rahix** [comment]
I take you managed to solve this by yourself?  Maybe you can quickly post here what the solutions was so others stumbling over this issue can see how to fix it?

**Comment by dominikwilkowski** [comment]
I'm actually not sure. I went back and forth between nightly and stable and tried a couple other things that I undid but in the end it started working. No idea why 😬
