### ISSUE TITLE
MPU 6050

### ISSUE THREAD

**Issue by sai-kalai** [Rahix/avr-hal-template#23]
Hi everyone,

first of all thanks for this amazing repo.

I want to use the MPU6050 on a project, so I'm thinking of building a hal for that.

I'm a beginner at rust, and I think this can be an exciting and challenging project.

Could you share any tips or relevant information?

thanks!

**Comment by Rahix** [comment]
It seems there is a driver for MPU6050 already: https://crates.io/crates/mpu6050

But please ask any questions via the `avr-hal` discussions forum here: https://github.com/Rahix/avr-hal/discussions
