### ISSUE TITLE
error[E0658]: use of unstable library feature 'proc_macro_byte_character'

### ISSUE THREAD

**Issue by vidurkhanal** [Rahix/avr-hal-template#30]
Compiling the template as it is compiles two errors: error[E0658]: use of unstable library feature 'proc_macro_byte_character' and error[E0658]: use of unstable library feature 'proc_macro_c_str_literals'. Setting crate features at the top of the entry main.rs doesn't solve the problem.

However changing channel from nightly-2024-03-22 to just nightly compiles the code. Was I supposed to update the channel in the tool chain.

**Comment by BenCaunt** [comment]
I'm having the same issues compiling for the Arduino Leonardo variant (not certain that it should matter).  

Compiled on `nightly-aarch64-apple-darwin unchanged - rustc 1.79.0-nightly (ccfcd950b 2024-04-15)`.

**Comment by Rahix** [comment]
More info in https://github.com/Rahix/avr-hal/issues/537.

**Comment by Rahix** [comment]
I've pushed commit 4c3e6b0ffcda ("Pin proc-macro2 to an older version") so new projects generated from the template should not have the problem anymore.
