### ISSUE TITLE
Would this template work for an Elegoo UNO board?

### ISSUE THREAD

**Issue by 5alv1** [Rahix/avr-hal-template#35]
As the title, I have an Elegoo board, I'm not sure if this would work because the registers are not the same as the original arduino Board, but I figured since I can already use the Arduino IDE this might work too, does it? If so, what board should I select when I generate a new project?

**Comment by Rahix** [comment]
From what I can tell, the Elegoo UNO also has an ATmega328P microcontroller and compatible pinout to the Arduino Uno.  So yes, you can use the template for your board, by using the Arduino Uno configuration.

**Comment by 5alv1** [comment]
Thank you!
